// <auto-generated />
using MagicPonySparkleLand.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace MagicPonySparkleLand.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180205002044_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MagicPonySparkleLand.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("MagicPonySparkleLand.Models.Message", b =>
                {
                    b.HasBaseType("MagicPonySparkleLand.Models.User");

                    b.Property<DateTime>("Date");

                    b.Property<int>("MessageID");

                    b.Property<string>("MessageText");

                    b.ToTable("Message");

                    b.HasDiscriminator().HasValue("Message");
                });
#pragma warning restore 612, 618
        }
    }
}
